### ISSUE TITLE
pycharm 2024.3 error when show numpy array in function

### ISSUE THREAD

**Issue by sunbuny** [srwi/PyCharm-PixelLens#36]
An exception occurred in the plugin.

### Environment:
- Plugin Version: 0.3.1
- PyCharm Version: 2024.3 (PyCharm)
- Operating System: Windows 10 10.0

### Exception details:
```js
Error evaluating expression Traceback (most recent call last):
  File "C:\Users\sunbin\AppData\Local\Programs\PyCharm Professional\plugins\python-ce\helpers\pydev\_pydevd_bundle\pydevd_comm.py", line 1569, in do_it
    result = pydevd_vars.evaluate_expression(self.thread_id, self.frame_id, self.expression, self.doExec)
  File "C:\Users\sunbin\AppData\Local\Programs\PyCharm Professional\plugins\python-ce\helpers\pydev\_pydevd_bundle\pydevd_vars.py", line 461, in evaluate_expression
    return eval_func(expression, updated_globals, frame, doExec, get_eval_exception_msg)
  File "C:\Users\sunbin\AppData\Local\Programs\PyCharm Professional\plugins\python\helpers-pro\pydevd_asyncio\pydevd_asyncio_utils.py", line 95, in _eval_async_expression
    Exec(expression, global_names, frame.f_locals)
    ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunbin\AppData\Local\Programs\PyCharm Professional\plugins\python-ce\helpers\pydev\_pydevd_bundle\pydevd_exec2.py", line 3, in Exec
    exec(exp, global_vars, local_vars)
    ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 1, in <module>
NameError: name '__srwi_pixellens_data' is not defined
com.jetbrains.python.debugger.pydev.AbstractCommand.processResponse(AbstractCommand.java:235)
com.jetbrains.python.debugger.pydev.EvaluateCommand.processResponse(EvaluateCommand.java:43)
com.jetbrains.python.debugger.pydev.AbstractCommand.execute(AbstractCommand.java:166)
com.jetbrains.python.debugger.pydev.RemoteDebugger.executeCommand(RemoteDebugger.java:797)
com.jetbrains.python.debugger.pydev.RemoteDebugger.evaluate(RemoteDebugger.java:164)
com.jetbrains.python.debugger.pydev.ClientModeMultiProcessDebugger.evaluate(ClientModeMultiProcessDebugger.java:187)
com.jetbrains.python.debugger.PyDebugProcess.evaluate(PyDebugProcess.java:813)
com.jetbrains.python.debugger.PyDebugProcess.evaluate(PyDebugProcess.java:809)
com.github.srwi.pixellens.interop.Python.executeStatement(Python.kt:21)
com.github.srwi.pixellens.imageProviders.ImageProvider.cleanUpData(ImageProvider.kt:64)
com.github.srwi.pixellens.imageProviders.ImageProvider.getBatchData(ImageProvider.kt:41)
com.github.srwi.pixellens.imageProviders.ImageProvider.getBatchByExpression(ImageProvider.kt:31)
com.github.srwi.pixellens.actions.ViewAsImageAction$actionPerformed$1.run(ViewAsImageAction.kt:29)
com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:491)
com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:133)
com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsynchronously$7(CoreProgressManager.java:542)
com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:249)
com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:98)
com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:223)
com.intellij.platform.diagnostic.telemetry.helpers.TraceKt.use(trace.kt:45)
com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:222)
com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$14(CoreProgressManager.java:674)
com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:749)
com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:705)
com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:673)
com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:79)
com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:203)
com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:98)
com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$5(ProgressRunner.java:249)
com.intellij.openapi.progress.impl.ProgressRunner$ProgressRunnable.run(ProgressRunner.java:502)
com.intellij.openapi.progress.impl.ProgressRunner.lambda$launchTask$18(ProgressRunner.java:467)
com.intellij.util.concurrency.ChildContext$runInChildContext$1.invoke(propagation.kt:101)
com.intellij.util.concurrency.ChildContext$runInChildContext$1.invoke(propagation.kt:101)
com.intellij.util.concurrency.ChildContext.runInChildContext(propagation.kt:107)
com.intellij.util.concurrency.ChildContext.runInChildContext(propagation.kt:101)
com.intellij.openapi.progress.impl.ProgressRunner.lambda$launchTask$19(ProgressRunner.java:463)
java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:735)
java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:732)
java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:732)
java.base/java.lang.Thread.run(Thread.java:1583)
```

### Steps to reproduce:
1. [Please fill in the steps to reproduce the issue]

### Code snippet:
```python
import numpy as np
import cv2
import sys

def _thinningIteration(im, iter):
    """
    Perform one thinning iteration using Zhang-Suen thinning algorithm.
    Parameters:
        im   - Binary image (NumPy array) with 0s and 1s.
        iter - Iteration index (0 or 1).
    Returns:
        Updated binary image after thinning.
    """
    I, M = im, np.zeros(im.shape, dtype=np.uint8)
    rows, cols = im.shape

    for i in range(1, rows - 1):
        for j in range(1, cols - 1):
            p2 = I[i-1, j]
            p3 = I[i-1, j+1]
            p4 = I[i, j+1]
            p5 = I[i+1, j+1]
            p6 = I[i+1, j]
            p7 = I[i+1, j-1]
            p8 = I[i, j-1]
            p9 = I[i-1, j-1]

            # Calculate A (number of 0->1 transitions in the 8 neighbors)
            A = ((p2 == 0 and p3 == 1) + (p3 == 0 and p4 == 1) +
                 (p4 == 0 and p5 == 1) + (p5 == 0 and p6 == 1) +
                 (p6 == 0 and p7 == 1) + (p7 == 0 and p8 == 1) +
                 (p8 == 0 and p9 == 1) + (p9 == 0 and p2 == 1))

            # Calculate B (number of 1s in the 8 neighbors)
            B = p2 + p3 + p4 + p5 + p6 + p7 + p8 + p9

            # Conditional masks
            m1 = (p2 * p4 * p6) if iter == 0 else (p2 * p4 * p8)
            m2 = (p4 * p6 * p8) if iter == 0 else (p2 * p6 * p8)

            # Thinning condition
            if A == 1 and 2 <= B <= 6 and m1 == 0 and m2 == 0:
                M[i, j] = 1

    # Update the image by removing marked pixels
    return I & ~M



def thinning(src):
	dst = (src.copy() / 255).astype(np.uint8)
	prev = np.zeros(src.shape[:2], np.uint8)
	diff = None

	while True:
		dst = _thinningIteration(dst, 0)
		dst = _thinningIteration(dst, 1)
		diff = np.absolute(dst - prev)
		prev = dst.copy()
		if np.sum(diff) == 0:
			break

	return dst * 255

if __name__ == "__main__":
	src = cv2.imread("data/spring0.bmp", cv2.IMREAD_ANYCOLOR)
	if src is None:
		sys.exit()
	if src.ndim == 3:
		bw = cv2.cvtColor(src, cv2.COLOR_BGR2GRAY)
	else:
		bw = src
	_, bw2 = cv2.threshold(bw, 10, 255, cv2.THRESH_BINARY)
	bw2 = thinning(bw2)
	cv2.imwrite("output.png", bw2)
	cv2.imshow("src", bw)
	cv2.imshow("thinning", bw2)
	cv2.waitKey()

```
breakpoint at line 52, and show the numpy array dst

**Comment by srwi** [comment]
Hi @sunbuny, I spent some time trying to think of a reason why this might be happening. I am having a hard time as I am unable to reproduce the problem with the provided code.

I have a few questions that might help me:

1. Does PixelLens work in other scenarios?
2. Is the error 100% reproducible in your code example?
3. Did the problem only appear after updating to PyCharm 2024.3?
4. Could you please try the following code and see if it happens there as well?
    
        import numpy as np
        img = np.random.randint(0, 2, (100, 100), dtype=np.uint8)
        pass
    If it doesn't happen with that code, would it be possible for you to provide the spring0.bmp file as well?

I might have to add some further logging output in a future release to be able to debug this in more detail.

**Comment by sunbuny** [comment]
Hi，@srwi. Thanks so much for you quick response. 
1. When I have the breakpoint at line 83, the *src*, *bw2* show correctly. There is no problem. But when i have the breakpoint at line 52, a error raise.
2. Yes, the problem reprodue in my env.
3. I only try the PixelLens at PyCharm 2024.3
4. This test case works fine, there is no problem.

The spring0.bmp.
[spring0.zip](https://github.com/user-attachments/files/17941367/spring0.zip)

By the way, I use the python 3.13 that might cause problem too.

**Comment by srwi** [comment]
Hi @sunbuny, sorry for the late reply. I had some time yesterday and released a new version that _might_ help a little bit in debugging. Could you please update to version 0.3.2 and try your code example again and provide the error message? After that, please navigate to Settings > Tools > PixelLens and check "Always use evaluate transmission" and try again? Please also provide the error message, if it fails.

**Comment by sunbuny** [comment]
com.jetbrains.python.debugger.PyDebuggerException: Error evaluating expression Traceback (most recent call last):
  File "C:\Users\sunbin\AppData\Local\Programs\PyCharm Professional\plugins\python-ce\helpers\pydev\_pydevd_bundle\pydevd_comm.py", line 1569, in do_it
    result = pydevd_vars.evaluate_expression(self.thread_id, self.frame_id, self.expression, self.doExec)
  File "C:\Users\sunbin\AppData\Local\Programs\PyCharm Professional\plugins\python-ce\helpers\pydev\_pydevd_bundle\pydevd_vars.py", line 461, in evaluate_expression
    return eval_func(expression, updated_globals, frame, doExec, get_eval_exception_msg)
  File "C:\Users\sunbin\AppData\Local\Programs\PyCharm Professional\plugins\python\helpers-pro\pydevd_asyncio\pydevd_asyncio_utils.py", line 95, in _eval_async_expression
    Exec(expression, global_names, frame.f_locals)
    ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunbin\AppData\Local\Programs\PyCharm Professional\plugins\python-ce\helpers\pydev\_pydevd_bundle\pydevd_exec2.py", line 3, in Exec
    exec(exp, global_vars, local_vars)
    ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 18, in <module>
NameError: name '__srwi_pixellens_image_provider' is not defined
com.jetbrains.python.debugger.pydev.AbstractCommand.processResponse(AbstractCommand.java:235)
com.jetbrains.python.debugger.pydev.EvaluateCommand.processResponse(EvaluateCommand.java:43)
com.jetbrains.python.debugger.pydev.AbstractCommand.execute(AbstractCommand.java:166)
com.jetbrains.python.debugger.pydev.RemoteDebugger.executeCommand(RemoteDebugger.java:797)
com.jetbrains.python.debugger.pydev.RemoteDebugger.evaluate(RemoteDebugger.java:164)
com.jetbrains.python.debugger.pydev.ClientModeMultiProcessDebugger.evaluate(ClientModeMultiProcessDebugger.java:187)
com.jetbrains.python.debugger.PyDebugProcess.evaluate(PyDebugProcess.java:813)
com.jetbrains.python.debugger.PyDebugProcess.evaluate(PyDebugProcess.java:809)
com.github.srwi.pixellens.interop.Python.executeStatement(Python.kt:21)
com.github.srwi.pixellens.imageProviders.ImageProvider.prepareData(ImageProvider.kt:49)
com.github.srwi.pixellens.imageProviders.ImageProvider.getBatchData(ImageProvider.kt:37)
com.github.srwi.pixellens.imageProviders.ImageProvider.getBatchByExpression(ImageProvider.kt:31)
com.github.srwi.pixellens.actions.ViewAsImageAction$actionPerformed$1.run(ViewAsImageAction.kt:29)
com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:491)
com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:133)
com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsynchronously$7(CoreProgressManager.java:542)
com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:249)
com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:98)
com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:223)
com.intellij.platform.diagnostic.telemetry.helpers.TraceKt.use(trace.kt:45)
com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:222)
com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$14(CoreProgressManager.java:674)
com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:749)
com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:705)
com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:673)
com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:79)
com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:203)
com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:98)
com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$5(ProgressRunner.java:249)
com.intellij.openapi.progress.impl.ProgressRunner$ProgressRunnable.run(ProgressRunner.java:502)
com.intellij.openapi.progress.impl.ProgressRunner.lambda$launchTask$18(ProgressRunner.java:467)
com.intellij.util.concurrency.ChildContext$runInChildContext$1.invoke(propagation.kt:101)
com.intellij.util.concurrency.ChildContext$runInChildContext$1.invoke(propagation.kt:101)
com.intellij.util.concurrency.ChildContext.runInChildContext(propagation.kt:107)
com.intellij.util.concurrency.ChildContext.runInChildContext(propagation.kt:101)
com.intellij.openapi.progress.impl.ProgressRunner.lambda$launchTask$19(ProgressRunner.java:463)
java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:735)
java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:732)
java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:732)
java.base/java.lang.Thread.run(Thread.java:1583)

**Comment by srwi** [comment]
Hi @sunbuny, sorry to bother you again. I released version 0.4.0 of PixelLens which slightly changes the way errors are logged. This should not fix the issue but it might produce a more telling error message. Would you mind trying it again and sharing the output?

Regarding the actual error, I must admit, I am a bit clueless. Basically this is what's happening:

```py
foo = "bar"
del foo  # This causes: "NameError: name 'foo' is not defined"
```

Perhaps you can see how this is confusing me. 😅

**Comment by sunbuny** [comment]
Hi, @srwi. Thank you so much for still working on this small problem. I will definitely try the 0.4.0 version. I will also provide you with more information about this issue. It seems that PixelLens works perfectly when the Python version is 3.7, which is weird. It might also be a PyCharm problem.

And here is the exception output:
```
com.jetbrains.python.debugger.PyDebuggerException: Error evaluating expression Traceback (most recent call last):
  File "C:\Users\sunbin\AppData\Local\Programs\PyCharm Professional\plugins\python-ce\helpers\pydev\_pydevd_bundle\pydevd_comm.py", line 1569, in do_it
    result = pydevd_vars.evaluate_expression(self.thread_id, self.frame_id, self.expression, self.doExec)
  File "C:\Users\sunbin\AppData\Local\Programs\PyCharm Professional\plugins\python-ce\helpers\pydev\_pydevd_bundle\pydevd_vars.py", line 461, in evaluate_expression
    return eval_func(expression, updated_globals, frame, doExec, get_eval_exception_msg)
  File "C:\Users\sunbin\AppData\Local\Programs\PyCharm Professional\plugins\python\helpers-pro\pydevd_asyncio\pydevd_asyncio_utils.py", line 95, in _eval_async_expression
    Exec(expression, global_names, frame.f_locals)
    ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunbin\AppData\Local\Programs\PyCharm Professional\plugins\python-ce\helpers\pydev\_pydevd_bundle\pydevd_exec2.py", line 3, in Exec
    exec(exp, global_vars, local_vars)
    ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 18, in <module>
NameError: name '__srwi_pixellens_image_provider' is not defined
com.jetbrains.python.debugger.pydev.AbstractCommand.processResponse(AbstractCommand.java:235)
com.jetbrains.python.debugger.pydev.EvaluateCommand.processResponse(EvaluateCommand.java:43)
com.jetbrains.python.debugger.pydev.AbstractCommand.execute(AbstractCommand.java:166)
com.jetbrains.python.debugger.pydev.RemoteDebugger.executeCommand(RemoteDebugger.java:797)
com.jetbrains.python.debugger.pydev.RemoteDebugger.evaluate(RemoteDebugger.java:164)
com.jetbrains.python.debugger.pydev.ClientModeMultiProcessDebugger.evaluate(ClientModeMultiProcessDebugger.java:187)
com.jetbrains.python.debugger.PyDebugProcess.evaluate(PyDebugProcess.java:813)
com.jetbrains.python.debugger.PyDebugProcess.evaluate(PyDebugProcess.java:809)
com.github.srwi.pixellens.interop.Python.executeStatement(Python.kt:21)
com.github.srwi.pixellens.imageProviders.ImageProvider.prepareData(ImageProvider.kt:49)
com.github.srwi.pixellens.imageProviders.ImageProvider.getBatchData(ImageProvider.kt:37)
com.github.srwi.pixellens.imageProviders.ImageProvider.getBatchByExpression(ImageProvider.kt:31)
com.github.srwi.pixellens.actions.ViewAsImageAction$actionPerformed$1.run(ViewAsImageAction.kt:29)
com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:491)
com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:133)
com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsynchronously$7(CoreProgressManager.java:542)
com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:249)
com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:98)
com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:223)
com.intellij.platform.diagnostic.telemetry.helpers.TraceKt.use(trace.kt:45)
com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:222)
com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$14(CoreProgressManager.java:674)
com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:749)
com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:705)
com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:673)
com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:79)
com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:203)
com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:98)
com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$5(ProgressRunner.java:249)
com.intellij.openapi.progress.impl.ProgressRunner$ProgressRunnable.run(ProgressRunner.java:502)
com.intellij.openapi.progress.impl.ProgressRunner.lambda$launchTask$18(ProgressRunner.java:467)
com.intellij.util.concurrency.ChildContext$runInChildContext$1.invoke(propagation.kt:101)
com.intellij.util.concurrency.ChildContext$runInChildContext$1.invoke(propagation.kt:101)
com.intellij.util.concurrency.ChildContext.runInChildContext(propagation.kt:107)
com.intellij.util.concurrency.ChildContext.runInChildContext(propagation.kt:101)
com.intellij.openapi.progress.impl.ProgressRunner.lambda$launchTask$19(ProgressRunner.java:463)
java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:735)
java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:732)
java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:732)
java.base/java.lang.Thread.run(Thread.java:1583)
```

**Comment by srwi** [comment]
Thanks for the additional information. Unfortunately I can't reproduce it on any version of Python and PyCharm which really makes this painful to debug. 😅 Hearing that the Debug Image Viewer also suffers from the same problem really points towards it being a PyCharm bug but nonetheless there might be a workaround.

Regarding the error output, it looks like the output you provided is still from PixelLens 0.3.2. Did you maybe forget to restart PyCharm after updating to PixelLens 0.4.0?

Thanks so much for your patience.

**Comment by srwi** [comment]
I was finally able to reproduce the bug. For me it only happens in Python 3.13.0. Once I update to Python 3.13.1 the problem is resolved. Could you please check that on your side as well? If you do so, please make sure to delete and recreate the virtual environment you may be using.

**Comment by sunbuny** [comment]
Thank you so much! Yes, my Python version was 3.13.0, and after updating to Python 3.13.1, the error disappeared. Thank you again for taking the time to help me solve my small problem. Also, PixelLens is a great project!

**Comment by sunbuny** [comment]
Also, do you have any plans to port PixelLens to CLion? Even though CLion has an official plugin to display cv::Mat, it is still closed-source. If PixelLens also supports CLion, it will reach the next stage.

**Comment by srwi** [comment]
Awesome, thank you!

I created a ticket for CLion support (#52). Not sure though when I'll be able to work on it.
